apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: web-container
        image: mathvicky/my-app:2e6844f546118a258669131959632d3536e8f7a2
        ports:
        - containerPort: 80
